export const availableRoles = [
  'Front-End Developer',
  'Back-End Developer',
  'Full-Stack Developer',
  'Software Developer',
  'Software Engineer',
  'Web Developer',
  'Mobile Developer',
  'Desktop Developer',
  'DevOps Engineer',
  'Cloud Engineer',
  'Data Engineer',
  'Data Scientist',
  'Machine Learning Engineer',
  'AI Engineer',
  'Cybersecurity Engineer',
  'Security Engineer',
  'QA Engineer',
  'Test Engineer',
  'Game Developer',
  'UI Developer',
  'UX Developer',
  'UI/UX Designer',
  'Product Designer',
  'Product Manager',
  'Project Manager',
  'Technical Lead',
  'Engineering Manager',
  'System Administrator',
  'Database Administrator',
  'Solutions Architect',
  'Software Architect',
];
